factor = @{ ("+" | "-")? ~ ASCII_DIGIT+ ~("." ~ ASCII_DIGIT+)? }
compound = @{ ASCII_ALPHANUMERIC ~ (("_" | "-" )* ~ ASCII_ALPHANUMERIC)* }
factor_compound = { (factor ~ " "+)? ~ compound }

operation = _{ add | subtract | equal }
    add      = { "+" }
    subtract = { "-" }
    equal    = { PUSH("=") }

reaction = { SOI ~ (" "+)? ~ factor_compound ~ " "+ ~ (operation ~ " "+ ~ factor_compound ~ (" "+ | EOI))* ~ EOI }
